# -*- python -*-
#
Import('env')
import eups, os

doxygen_conf = "doxygen.conf"
htmlDir = "htmlDir"

def writeDoxygen_conf(products=None):

    import writeDoxyConfig

    if products == None:
        products = []
        for prod in eups.Eups().getSetupProducts():
            products.append(prod.name)

    doxyconfScript = writeDoxyConfig.main(products, verbose=True, htmlDir=htmlDir)

    fp = open(doxygen_conf, 'w')
    fp.write(doxyconfScript + "\n")
    fp.close()


# Following creates doxygen config file used to generate cross-reference
# between all explicitly named packages
products = ["meas_astrom", "afw"]

# Following creates doxygen config file used to generate cross-reference
# documentation for ALL packages currently 'setup'.
#products = None

# Override crosslink-or-not with an environment variable
xlinkdoxy = int(os.environ.get('xlinkdoxy',None))
if xlinkdoxy == 1 :
    products = None

writeDoxygen_conf(products)


env.Clean(".", htmlDir)
doxy = env.Doxygen(htmlDir, doxygen_conf)

